name: Automatic Deployment

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome
        run: echo Start deploying
      - name: Checkout git
        uses: actions/checkout@v3
      - name: Deploy static to Cloudflare Pages
        run: curl -X POST ${{ secrets.CLOUDFLARE_PAGES_DEPLOY_HOOK }}
